<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
   function($class) {
      static $classes = null;
      if ($classes === null) {
         $classes = array(
            'interfacewriter' => '/InterfaceWriter.php',
            'noimplementedmethodsiterator' => '/Filters/NoImplementedMethodsIterator.php',
            'noinheritedmethodsiterator' => '/Filters/NoInheritedMethodsIterator.php',
            'nomagicmethodsiterator' => '/Filters/NoMagicMethodsIterator.php',
            'nooldstyleconstructoriterator' => '/Filters/NoOldStyleConstructorIterator.php',
            'notraitmethodsiterator' => '/Filters/NoTraitMethodsIterator.php',
            'regexmethoditerator' => '/Filters/RegexMethodIterator.php'
          );
      }
      $cn = strtolower($class);
      if (isset($classes[$cn])) {
         require __DIR__ . $classes[$cn];
      }
   }
);
// @codeCoverageIgnoreEnd
